name: Build Binary and Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build binary using Buildx (with auth)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: slippc-builder
          load: true
          platforms: linux/amd64

      - name: Copy binary out of container
        run: |
          CONTAINER_ID=$(docker create slippc-builder)
          docker cp "$CONTAINER_ID":/src/slippc/slippc ./lambda/slippc
          docker rm "$CONTAINER_ID"

      - name: Ensure binary is executable
        run: chmod +x lambda/slippc

      - name: Install Lambda dependencies
        working-directory: lambda
        run: npm ci

      - name: Zip Lambda source
        working-directory: lambda
        run: zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip